/**
 * The service worker's decisions, kept out of src/service-worker.ts so they
 * can be unit tested without a ServiceWorkerGlobalScope. See
 * docs/service-worker.md for the whole design and how to debug it.
 */

/**
 * The kill switch. Set to false and deploy, and the worker is removed from
 * every browser that has it, leaving the site as if it had never existed:
 *
 * - the layout stops registering it and unregisters any registration it
 *   finds, on the visitor's next page load; and
 * - the worker itself, when the browser picks up the new build, deletes its
 *   cache, unregisters and reloads its open tabs once.
 *
 * Both halves read this one constant. If only the worker switched off, the
 * layout would re-register it on the reload the worker triggers, and the
 * tab would reload forever.
 */
export const SERVICE_WORKER_ENABLED = true;

/** Every cache this worker owns starts with this, so activate can find old ones. */
export const CACHE_PREFIX = 'ghostbase-offline-';

/**
 * Set on every response the worker makes up rather than passes through — the
 * offline page, today. In DevTools' Network panel a 503 carrying this header
 * is the worker, not the server; a 503 without it is the server.
 */
export const SW_HEADER = 'X-Ghostbase-SW';

/**
 * Whether a navigation that failed to reach the network may be answered with
 * the offline page, or should fail the way it would with no worker at all.
 *
 * /auth/ is left alone: the OAuth callback carries a one-time code, and the
 * offline page reloads the URL it stands in for once the connection is back —
 * which would replay a spent code into an error. Better the browser's own
 * page there, where a reload is the reader's decision.
 */
export function fallbackAllowed(url: URL): boolean {
	return !url.pathname.startsWith('/auth/');
}

export type OfflineFonts = {
	display?: string;
	body?: string;
	mono?: string;
};

/**
 * The three faces the offline page is set in, found in the build by the
 * names fontsource gives them. Vite fingerprints the files, so the URLs are
 * only known at build time — which is also why the page is generated by the
 * worker rather than kept as a static file.
 *
 * A face that is not found is left out and the page falls back to a system
 * font. A dependency bump that renames a file costs the offline page its
 * typeface, never the offline page.
 */
export function pickFonts(build: string[]): OfflineFonts {
	const find = (name: string) => build.find((path) => path.includes(`/${name}.`) && path.endsWith('.woff2'));
	return {
		display: find('instrument-serif-latin-400-normal'),
		body: find('archivo-latin-wght-normal'),
		mono: find('jetbrains-mono-latin-wght-normal')
	};
}
